/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enigma
 */
public class ContentKredensial extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContentStats
     */
    public ContentKredensial() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        this.LoadData();
    }
    
    private void LoadData() {
        DefaultTableModel model = (DefaultTableModel) TableKredensial.getModel();
        var data = Model.Kredensial.Get();
        var rows = new Object[4];
        for (HashMap<String, String> item : data) {
            rows[0] = item.get("id");
            rows[1] = item.get("username");
            rows[2] = item.get("password");
            rows[3] = item.get("level");
            model.addRow(rows);
        }
    }
    
    private void ClearData() {
        DefaultTableModel model = (DefaultTableModel) TableKredensial.getModel();
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }
    }
    
    private void FieldClear() {
        fieldUsername.setText("");
        fieldPassword.setText("");
        cboxLevel.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ScrollPanel = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        cboxLevel = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableKredensial = new View.components.CustomTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(new java.awt.Color(255, 255, 255));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(980, 700));
        setMinimumSize(new java.awt.Dimension(980, 700));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(980, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ScrollPanel.setBackground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setBorder(null);
        ScrollPanel.setForeground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setPreferredSize(new java.awt.Dimension(980, 700));

        MainPanel.setBackground(new java.awt.Color(249, 249, 249));
        MainPanel.setForeground(new java.awt.Color(249, 249, 249));
        MainPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        MainPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        MainPanel.setPreferredSize(new java.awt.Dimension(980, 700));
        MainPanel.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setForeground(new java.awt.Color(249, 249, 249));

        fieldUsername.setBackground(new java.awt.Color(76, 86, 106));
        fieldUsername.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        fieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldUsername.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldUsername.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldUsername.setOpaque(true);
        fieldUsername.setPreferredSize(new java.awt.Dimension(101, 40));

        fieldPassword.setBackground(new java.awt.Color(76, 86, 106));
        fieldPassword.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(255, 255, 255));
        fieldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldPassword.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldPassword.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldPassword.setOpaque(true);
        fieldPassword.setPreferredSize(new java.awt.Dimension(101, 40));

        lblUsername.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(67, 76, 94));
        lblUsername.setText("Username");
        lblUsername.setMaximumSize(new java.awt.Dimension(117, 40));
        lblUsername.setMinimumSize(new java.awt.Dimension(117, 40));
        lblUsername.setPreferredSize(new java.awt.Dimension(117, 40));

        lblLevel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(67, 76, 94));
        lblLevel.setText("Hak Akses");
        lblLevel.setMaximumSize(new java.awt.Dimension(119, 40));
        lblLevel.setMinimumSize(new java.awt.Dimension(119, 40));
        lblLevel.setPreferredSize(new java.awt.Dimension(119, 40));

        lblPassword.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(67, 76, 94));
        lblPassword.setText("Password");
        lblPassword.setMaximumSize(new java.awt.Dimension(49, 40));
        lblPassword.setMinimumSize(new java.awt.Dimension(49, 40));
        lblPassword.setPreferredSize(new java.awt.Dimension(49, 40));

        btnSimpan.setBackground(new java.awt.Color(76, 86, 106));
        btnSimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(249, 249, 249));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setFocusPainted(false);
        btnSimpan.setOpaque(true);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(191, 97, 106));
        btnHapus.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(249, 249, 249));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 97, 106), 10));
        btnHapus.setContentAreaFilled(false);
        btnHapus.setFocusPainted(false);
        btnHapus.setOpaque(true);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(76, 86, 106));
        btnUbah.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(249, 249, 249));
        btnUbah.setText("Ubah");
        btnUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        btnUbah.setContentAreaFilled(false);
        btnUbah.setFocusPainted(false);
        btnUbah.setOpaque(true);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(191, 97, 106));
        btnBatal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(249, 249, 249));
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 97, 106), 10));
        btnBatal.setContentAreaFilled(false);
        btnBatal.setFocusPainted(false);
        btnBatal.setOpaque(true);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        cboxLevel.setBackground(new java.awt.Color(76, 86, 106));
        cboxLevel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cboxLevel.setForeground(new java.awt.Color(255, 255, 255));
        cboxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "owner", "admin", "operator" }));
        cboxLevel.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addComponent(btnHapus)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        MainPanel.add(jPanel1);

        TableKredensial.setBackground(new java.awt.Color(236, 239, 244));
        TableKredensial.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        TableKredensial.setForeground(new java.awt.Color(76, 86, 106));
        TableKredensial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableKredensial.setToolTipText("");
        TableKredensial.setDoubleBuffered(true);
        TableKredensial.setFocusable(false);
        TableKredensial.setGridColor(new java.awt.Color(67, 76, 94));
        TableKredensial.setRowHeight(30);
        TableKredensial.setSelectionBackground(new java.awt.Color(216, 222, 233));
        TableKredensial.setSelectionForeground(new java.awt.Color(67, 76, 94));
        TableKredensial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableKredensial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableKredensial.setShowGrid(false);
        TableKredensial.setShowHorizontalLines(true);
        TableKredensial.getTableHeader().setReorderingAllowed(false);
        TableKredensial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKredensialMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableKredensial);

        MainPanel.add(jScrollPane2);

        ScrollPanel.setViewportView(MainPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(ScrollPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        var username = fieldUsername.getText();
        var password = classes.Helper.CreateSha256(fieldPassword.getText());
        var level = cboxLevel.getSelectedItem().toString();
        Model.Kredensial.Add(username, password, level);
        this.ClearData();
        this.LoadData();
        this.FieldClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            Model.Kredensial.Destroy(key);
            this.ClearData();
            this.LoadData();
            this.FieldClear();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        var username = fieldUsername.getText();
        var password = classes.Helper.CreateSha256(fieldPassword.getText());
        var level = cboxLevel.getSelectedItem().toString();
        Model.Kredensial.Edit(key, username, password, level);
        this.ClearData();
        this.LoadData();
        this.FieldClear();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void TableKredensialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKredensialMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableKredensial.getModel();
        int idx = TableKredensial.getSelectedRow();
        key = Integer.parseInt(model.getValueAt(idx, 0).toString());
        fieldUsername.setText(model.getValueAt(idx, 1).toString());
        fieldPassword.setText(model.getValueAt(idx, 2).toString());
        cboxLevel.setSelectedItem(model.getValueAt(idx, 3).toString());
    }//GEN-LAST:event_TableKredensialMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.FieldClear();
        TableKredensial.clearSelection();
    }//GEN-LAST:event_btnBatalActionPerformed

    // reserved object
    private static int key;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTable TableKredensial;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cboxLevel;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
