/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author enigma
 */
public class ContentStats extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContentStats
     */
    public ContentStats() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ScrollPanel = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(null);
        setForeground(new java.awt.Color(255, 102, 102));
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(980, 700));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(980, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ScrollPanel.setBackground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setBorder(null);
        ScrollPanel.setForeground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setPreferredSize(new java.awt.Dimension(980, 700));

        MainPanel.setBackground(new java.awt.Color(249, 249, 249));
        MainPanel.setForeground(new java.awt.Color(249, 249, 249));
        MainPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Data Statistik");
        MainPanel.add(jLabel1, new java.awt.GridBagConstraints());

        ScrollPanel.setViewportView(MainPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(ScrollPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
