/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enigma
 */
public class ContentPakan extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContentStats
     */
    public ContentPakan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        fieldDeskripsi.setLineWrap(true);
        fieldDeskripsi.setWrapStyleWord(true);
        this.LoadData();
        
        cboxKategori.addItem("Pakan Hewan Ternak");
        cboxKategori.addItem("Pakan Hewan Peliharaan");
        cboxKategori.addItem("Pakan Tumbuhan");
        cboxKategori.setSelectedIndex(-1);
        
        dataSatuan = Model.Satuan.Get();
        for (HashMap<String, String> data : dataSatuan) {
            cboxSatuan.addItem(data.get("satuan"));
        }
        cboxSatuan.setSelectedIndex(-1);
        
        dataSupplier = Model.Supplier.Get();
        for (HashMap<String, String> data : dataSupplier) {
            cboxSupplier.addItem(data.get("nama"));
        }
        cboxSupplier.setSelectedIndex(-1);
    }
    
    private void LoadData() {
        DefaultTableModel model = (DefaultTableModel) TablePakan.getModel();
        var data = Model.Pakan.Get();
        var rows = new Object[8];
        for (HashMap<String, String> item : data) {
            rows[0] = item.get("id");
            rows[1] = item.get("kode");
            rows[2] = item.get("nama");
            rows[3] = item.get("kategori");
            rows[4] = item.get("hewan");
            rows[5] = item.get("deskripsi");
            rows[6] = item.get("satuan_id");
            rows[7] = item.get("supplier_id");
            model.addRow(rows);
        }
    }
    
    private void ClearData() {
        DefaultTableModel model = (DefaultTableModel) TablePakan.getModel();
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }
    }
    
    private void FieldClear() {
        fieldKode.setText("");
        fieldNama.setText("");
        cboxKategori.setSelectedIndex(-1);
        fieldHewan.setText("");
        cboxSatuan.setSelectedIndex(-1);
        cboxSupplier.setSelectedIndex(-1);
        fieldDeskripsi.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ScrollPanel = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fieldKode = new javax.swing.JTextField();
        lblKode = new javax.swing.JLabel();
        lblSatuan = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        lblSupplier = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldDeskripsi = new javax.swing.JTextArea();
        lblNama = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        lblKategori = new javax.swing.JLabel();
        lblHewan = new javax.swing.JLabel();
        fieldHewan = new javax.swing.JTextField();
        cboxSatuan = new javax.swing.JComboBox<>();
        cboxSupplier = new javax.swing.JComboBox<>();
        cboxKategori = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePakan = new View.components.CustomTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(new java.awt.Color(255, 255, 255));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(980, 700));
        setMinimumSize(new java.awt.Dimension(980, 700));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(980, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ScrollPanel.setBackground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setBorder(null);
        ScrollPanel.setForeground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setPreferredSize(new java.awt.Dimension(980, 700));

        MainPanel.setBackground(new java.awt.Color(249, 249, 249));
        MainPanel.setForeground(new java.awt.Color(249, 249, 249));
        MainPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        MainPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        MainPanel.setPreferredSize(new java.awt.Dimension(980, 700));
        MainPanel.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setForeground(new java.awt.Color(249, 249, 249));

        fieldKode.setBackground(new java.awt.Color(76, 86, 106));
        fieldKode.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldKode.setForeground(new java.awt.Color(255, 255, 255));
        fieldKode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldKode.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldKode.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldKode.setOpaque(true);
        fieldKode.setPreferredSize(new java.awt.Dimension(101, 40));

        lblKode.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblKode.setForeground(new java.awt.Color(67, 76, 94));
        lblKode.setText("Kode Pakan");
        lblKode.setMaximumSize(new java.awt.Dimension(117, 40));
        lblKode.setMinimumSize(new java.awt.Dimension(117, 40));
        lblKode.setPreferredSize(new java.awt.Dimension(117, 40));

        lblSatuan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(67, 76, 94));
        lblSatuan.setText("Satuan");
        lblSatuan.setMaximumSize(new java.awt.Dimension(49, 40));
        lblSatuan.setMinimumSize(new java.awt.Dimension(49, 40));
        lblSatuan.setPreferredSize(new java.awt.Dimension(49, 40));

        btnSimpan.setBackground(new java.awt.Color(76, 86, 106));
        btnSimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(249, 249, 249));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setFocusPainted(false);
        btnSimpan.setOpaque(true);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(191, 97, 106));
        btnHapus.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(249, 249, 249));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 97, 106), 10));
        btnHapus.setContentAreaFilled(false);
        btnHapus.setFocusPainted(false);
        btnHapus.setOpaque(true);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(76, 86, 106));
        btnUbah.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(249, 249, 249));
        btnUbah.setText("Ubah");
        btnUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        btnUbah.setContentAreaFilled(false);
        btnUbah.setFocusPainted(false);
        btnUbah.setOpaque(true);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(191, 97, 106));
        btnBatal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(249, 249, 249));
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 97, 106), 10));
        btnBatal.setContentAreaFilled(false);
        btnBatal.setFocusPainted(false);
        btnBatal.setOpaque(true);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        lblSupplier.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(67, 76, 94));
        lblSupplier.setText("Supplier");
        lblSupplier.setMaximumSize(new java.awt.Dimension(117, 40));
        lblSupplier.setMinimumSize(new java.awt.Dimension(117, 40));
        lblSupplier.setPreferredSize(new java.awt.Dimension(117, 40));

        lblDeskripsi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblDeskripsi.setForeground(new java.awt.Color(67, 76, 94));
        lblDeskripsi.setText("Deskripsi");
        lblDeskripsi.setMaximumSize(new java.awt.Dimension(56, 40));
        lblDeskripsi.setMinimumSize(new java.awt.Dimension(56, 40));
        lblDeskripsi.setPreferredSize(new java.awt.Dimension(56, 40));

        fieldDeskripsi.setBackground(new java.awt.Color(76, 86, 106));
        fieldDeskripsi.setColumns(15);
        fieldDeskripsi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        fieldDeskripsi.setRows(3);
        fieldDeskripsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldDeskripsi.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane3.setViewportView(fieldDeskripsi);

        lblNama.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblNama.setForeground(new java.awt.Color(67, 76, 94));
        lblNama.setText("Nama Pakan");
        lblNama.setMaximumSize(new java.awt.Dimension(49, 40));
        lblNama.setMinimumSize(new java.awt.Dimension(49, 40));
        lblNama.setPreferredSize(new java.awt.Dimension(49, 40));

        fieldNama.setBackground(new java.awt.Color(76, 86, 106));
        fieldNama.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldNama.setForeground(new java.awt.Color(255, 255, 255));
        fieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldNama.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldNama.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldNama.setOpaque(true);
        fieldNama.setPreferredSize(new java.awt.Dimension(101, 40));

        lblKategori.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblKategori.setForeground(new java.awt.Color(67, 76, 94));
        lblKategori.setText("Kategori");
        lblKategori.setMaximumSize(new java.awt.Dimension(49, 40));
        lblKategori.setMinimumSize(new java.awt.Dimension(49, 40));
        lblKategori.setPreferredSize(new java.awt.Dimension(49, 40));

        lblHewan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblHewan.setForeground(new java.awt.Color(67, 76, 94));
        lblHewan.setText("Hewan");
        lblHewan.setMaximumSize(new java.awt.Dimension(49, 40));
        lblHewan.setMinimumSize(new java.awt.Dimension(49, 40));
        lblHewan.setPreferredSize(new java.awt.Dimension(49, 40));

        fieldHewan.setBackground(new java.awt.Color(76, 86, 106));
        fieldHewan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldHewan.setForeground(new java.awt.Color(255, 255, 255));
        fieldHewan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldHewan.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldHewan.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldHewan.setOpaque(true);
        fieldHewan.setPreferredSize(new java.awt.Dimension(101, 40));

        cboxSatuan.setBackground(new java.awt.Color(76, 86, 106));
        cboxSatuan.setBorder(null);

        cboxSupplier.setBackground(new java.awt.Color(76, 86, 106));

        cboxKategori.setBackground(new java.awt.Color(76, 86, 106));
        cboxKategori.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHewan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKode, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDeskripsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(cboxSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatal))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        MainPanel.add(jPanel1);

        TablePakan.setBackground(new java.awt.Color(236, 239, 244));
        TablePakan.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        TablePakan.setForeground(new java.awt.Color(76, 86, 106));
        TablePakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kode Pakan", "Nama Pakan", "Kategori", "Hewan", "Deskripsi", "Satuan", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePakan.setToolTipText("");
        TablePakan.setDoubleBuffered(true);
        TablePakan.setFocusable(false);
        TablePakan.setGridColor(new java.awt.Color(67, 76, 94));
        TablePakan.setRowHeight(30);
        TablePakan.setSelectionBackground(new java.awt.Color(216, 222, 233));
        TablePakan.setSelectionForeground(new java.awt.Color(67, 76, 94));
        TablePakan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablePakan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablePakan.setShowGrid(false);
        TablePakan.setShowHorizontalLines(true);
        TablePakan.getTableHeader().setReorderingAllowed(false);
        TablePakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePakanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablePakan);

        MainPanel.add(jScrollPane2);

        ScrollPanel.setViewportView(MainPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(ScrollPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        var kode = fieldKode.getText();
        var nama = fieldNama.getText();
        var kategori = cboxKategori.getSelectedItem().toString();
        var hewan = fieldHewan.getText();
        var satuan = Model.Satuan.Get(cboxSatuan.getSelectedItem().toString());
        var supplier = Model.Supplier.Get(cboxSupplier.getSelectedItem().toString());
        var deskripsi = fieldDeskripsi.getText();
        Model.Pakan.Add(kode, nama, kategori, hewan, deskripsi, satuan.get(0).get("id"), supplier.get(0).get("id"));
        this.ClearData();
        this.LoadData();
        this.FieldClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            Model.Pakan.Destroy(key);
            this.ClearData();
            this.LoadData();
            this.FieldClear();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        var kode = fieldKode.getText();
        var nama = fieldNama.getText();
        var kategori = cboxKategori.getSelectedItem().toString();
        var hewan = fieldHewan.getText();
        var satuan = Model.Satuan.Get(cboxSatuan.getSelectedItem().toString());
        var supplier = Model.Supplier.Get(cboxSupplier.getSelectedItem().toString());
        var deskripsi = fieldDeskripsi.getText();
        Model.Pakan.Edit(key, kode, nama, kategori, hewan, deskripsi, satuan.get(0).get("id"), supplier.get(0).get("id"));
        this.ClearData();
        this.LoadData();
        this.FieldClear();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void TablePakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePakanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TablePakan.getModel();
        int idx = TablePakan.getSelectedRow();
        key = Integer.parseInt(model.getValueAt(idx, 0).toString());
        fieldKode.setText(model.getValueAt(idx, 1).toString());
        fieldNama.setText(model.getValueAt(idx, 2).toString());
        cboxKategori.setSelectedItem(model.getValueAt(idx, 3).toString());
        fieldHewan.setText(model.getValueAt(idx, 4).toString());
        fieldDeskripsi.setText(model.getValueAt(idx, 5).toString());
        cboxSatuan.setSelectedItem(Model.Satuan.Get(Integer.parseInt(model.getValueAt(idx, 6).toString())).get(0).get("satuan"));
        cboxSupplier.setSelectedItem(Model.Supplier.Get(Integer.parseInt(model.getValueAt(idx, 7).toString())).get(0).get("nama"));
    }//GEN-LAST:event_TablePakanMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.FieldClear();
        TablePakan.clearSelection();
    }//GEN-LAST:event_btnBatalActionPerformed

    // reserved object
    private static int key;
    private static ArrayList<HashMap<String, String>> dataSatuan;
    private static ArrayList<HashMap<String, String>> dataSupplier;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTable TablePakan;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cboxKategori;
    private javax.swing.JComboBox<String> cboxSatuan;
    private javax.swing.JComboBox<String> cboxSupplier;
    private javax.swing.JTextArea fieldDeskripsi;
    private javax.swing.JTextField fieldHewan;
    private javax.swing.JTextField fieldKode;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblHewan;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblSupplier;
    // End of variables declaration//GEN-END:variables
}
