/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enigma
 */
public class ContentSatuan extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContentStats
     */
    public ContentSatuan() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        this.LoadData();
        fieldDeskripsi.setLineWrap(true);
        fieldDeskripsi.setWrapStyleWord(true);
    }
    
    private void LoadData() {
        DefaultTableModel model = (DefaultTableModel) TableSatuan.getModel();
        var data = Model.Satuan.Get();
        var rows = new Object[4];
        for (HashMap<String, String> item : data) {
            rows[0] = item.get("id");
            rows[1] = item.get("satuan");
            rows[2] = item.get("deskripsi");
            rows[3] = item.get("simbol");
            model.addRow(rows);
        }
    }
    
    private void ClearData() {
        DefaultTableModel model = (DefaultTableModel) TableSatuan.getModel();
        for (int i = model.getRowCount() - 1; i > -1; i--) {
            model.removeRow(i);
        }
    }
    
    private void FieldClear() {
        fieldSatuan.setText("");
        fieldDeskripsi.setText("");
        fieldSimbol.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ScrollPanel = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fieldSatuan = new javax.swing.JTextField();
        fieldSimbol = new javax.swing.JTextField();
        lblSatuan = new javax.swing.JLabel();
        lblSimbol = new javax.swing.JLabel();
        lblDeskripsi = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDeskripsi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSatuan = new View.components.CustomTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setForeground(new java.awt.Color(255, 255, 255));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(980, 700));
        setMinimumSize(new java.awt.Dimension(980, 700));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(980, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ScrollPanel.setBackground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setBorder(null);
        ScrollPanel.setForeground(new java.awt.Color(249, 249, 249));
        ScrollPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        ScrollPanel.setPreferredSize(new java.awt.Dimension(980, 700));

        MainPanel.setBackground(new java.awt.Color(249, 249, 249));
        MainPanel.setForeground(new java.awt.Color(249, 249, 249));
        MainPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        MainPanel.setMinimumSize(new java.awt.Dimension(980, 700));
        MainPanel.setPreferredSize(new java.awt.Dimension(980, 700));
        MainPanel.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setForeground(new java.awt.Color(249, 249, 249));

        fieldSatuan.setBackground(new java.awt.Color(76, 86, 106));
        fieldSatuan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldSatuan.setForeground(new java.awt.Color(255, 255, 255));
        fieldSatuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldSatuan.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldSatuan.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldSatuan.setOpaque(true);
        fieldSatuan.setPreferredSize(new java.awt.Dimension(101, 40));

        fieldSimbol.setBackground(new java.awt.Color(76, 86, 106));
        fieldSimbol.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldSimbol.setForeground(new java.awt.Color(255, 255, 255));
        fieldSimbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldSimbol.setMargin(new java.awt.Insets(10, 10, 10, 10));
        fieldSimbol.setMinimumSize(new java.awt.Dimension(64, 40));
        fieldSimbol.setOpaque(true);
        fieldSimbol.setPreferredSize(new java.awt.Dimension(101, 40));

        lblSatuan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblSatuan.setForeground(new java.awt.Color(67, 76, 94));
        lblSatuan.setText("Satuan");
        lblSatuan.setMaximumSize(new java.awt.Dimension(117, 40));
        lblSatuan.setMinimumSize(new java.awt.Dimension(117, 40));
        lblSatuan.setPreferredSize(new java.awt.Dimension(117, 40));

        lblSimbol.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblSimbol.setForeground(new java.awt.Color(67, 76, 94));
        lblSimbol.setText("Simbol");
        lblSimbol.setMaximumSize(new java.awt.Dimension(119, 40));
        lblSimbol.setMinimumSize(new java.awt.Dimension(119, 40));
        lblSimbol.setPreferredSize(new java.awt.Dimension(119, 40));

        lblDeskripsi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblDeskripsi.setForeground(new java.awt.Color(67, 76, 94));
        lblDeskripsi.setText("Deskripsi");
        lblDeskripsi.setMaximumSize(new java.awt.Dimension(49, 40));
        lblDeskripsi.setMinimumSize(new java.awt.Dimension(49, 40));
        lblDeskripsi.setPreferredSize(new java.awt.Dimension(49, 40));

        btnSimpan.setBackground(new java.awt.Color(76, 86, 106));
        btnSimpan.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(249, 249, 249));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setFocusPainted(false);
        btnSimpan.setOpaque(true);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(191, 97, 106));
        btnHapus.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(249, 249, 249));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 97, 106), 10));
        btnHapus.setContentAreaFilled(false);
        btnHapus.setFocusPainted(false);
        btnHapus.setOpaque(true);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(76, 86, 106));
        btnUbah.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(249, 249, 249));
        btnUbah.setText("Ubah");
        btnUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        btnUbah.setContentAreaFilled(false);
        btnUbah.setFocusPainted(false);
        btnUbah.setOpaque(true);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(191, 97, 106));
        btnBatal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(249, 249, 249));
        btnBatal.setText("Batal");
        btnBatal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 97, 106), 10));
        btnBatal.setContentAreaFilled(false);
        btnBatal.setFocusPainted(false);
        btnBatal.setOpaque(true);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        fieldDeskripsi.setBackground(new java.awt.Color(76, 86, 106));
        fieldDeskripsi.setColumns(15);
        fieldDeskripsi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        fieldDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        fieldDeskripsi.setRows(3);
        fieldDeskripsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 86, 106), 10));
        fieldDeskripsi.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(fieldDeskripsi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDeskripsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSatuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSimbol, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                    .addComponent(fieldSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSimbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
        );

        MainPanel.add(jPanel1);

        TableSatuan.setBackground(new java.awt.Color(236, 239, 244));
        TableSatuan.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        TableSatuan.setForeground(new java.awt.Color(76, 86, 106));
        TableSatuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Satuan", "Deskripsi", "Simbol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableSatuan.setToolTipText("");
        TableSatuan.setDoubleBuffered(true);
        TableSatuan.setFocusable(false);
        TableSatuan.setGridColor(new java.awt.Color(67, 76, 94));
        TableSatuan.setRowHeight(30);
        TableSatuan.setSelectionBackground(new java.awt.Color(216, 222, 233));
        TableSatuan.setSelectionForeground(new java.awt.Color(67, 76, 94));
        TableSatuan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableSatuan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableSatuan.setShowGrid(false);
        TableSatuan.setShowHorizontalLines(true);
        TableSatuan.getTableHeader().setReorderingAllowed(false);
        TableSatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSatuanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSatuan);

        MainPanel.add(jScrollPane2);

        ScrollPanel.setViewportView(MainPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(ScrollPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        var satuan = fieldSatuan.getText();
        var deskripsi = fieldDeskripsi.getText();
        var simbol = fieldSimbol.getText();
        Model.Satuan.Add(satuan, deskripsi, simbol);
        this.ClearData();
        this.LoadData();
        this.FieldClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(rootPane, "Apakah anda yakin?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            Model.Satuan.Destroy(key);
            this.ClearData();
            this.LoadData();
            this.FieldClear();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        var satuan = fieldSatuan.getText();
        var deskripsi = fieldDeskripsi.getText();
        var simbol = fieldSimbol.getText();
        Model.Satuan.Edit(key, satuan, deskripsi, simbol);
        this.ClearData();
        this.LoadData();
        this.FieldClear();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void TableSatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSatuanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TableSatuan.getModel();
        int idx = TableSatuan.getSelectedRow();
        key = Integer.parseInt(model.getValueAt(idx, 0).toString());
        fieldSatuan.setText(model.getValueAt(idx, 1).toString());
        fieldDeskripsi.setText(model.getValueAt(idx, 2).toString());
        fieldSimbol.setText(model.getValueAt(idx, 3).toString());
    }//GEN-LAST:event_TableSatuanMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.FieldClear();
        TableSatuan.clearSelection();
    }//GEN-LAST:event_btnBatalActionPerformed

    // reserved object
    private static int key;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTable TableSatuan;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextArea fieldDeskripsi;
    private javax.swing.JTextField fieldSatuan;
    private javax.swing.JTextField fieldSimbol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDeskripsi;
    private javax.swing.JLabel lblSatuan;
    private javax.swing.JLabel lblSimbol;
    // End of variables declaration//GEN-END:variables
}
