/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author enigma
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        lblBreadcrumb.setText("Dashboard");
        View.ContentStats obj = new View.ContentStats();
        ContentPanel.removeAll();
        ContentPanel.add(obj).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        HeaderPanel = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        SidebarPanel = new javax.swing.JPanel();
        UserPanel = new javax.swing.JPanel();
        UserPhoto = new javax.swing.JLabel();
        NavigationPanel = new javax.swing.JPanel();
        DashboardMenu = new javax.swing.JPanel();
        DashboardIcon = new javax.swing.JLabel();
        DashboardLabel = new javax.swing.JLabel();
        KaryawanMenu = new javax.swing.JPanel();
        KaryawanIcon = new javax.swing.JLabel();
        KaryawanLabel = new javax.swing.JLabel();
        KredensialMenu = new javax.swing.JPanel();
        KredensialIcon = new javax.swing.JLabel();
        KredensialLabel = new javax.swing.JLabel();
        SupplierMenu = new javax.swing.JPanel();
        SupplierIcon = new javax.swing.JLabel();
        SupplierLabel = new javax.swing.JLabel();
        SatuanMenu = new javax.swing.JPanel();
        SatuanIcon = new javax.swing.JLabel();
        SatuanLabel = new javax.swing.JLabel();
        PakanMenu = new javax.swing.JPanel();
        PakanIcon = new javax.swing.JLabel();
        PakanLabel = new javax.swing.JLabel();
        PersediaanMenu = new javax.swing.JPanel();
        PersediaanIcon = new javax.swing.JLabel();
        PersediaanLabel = new javax.swing.JLabel();
        PenjualanMenu = new javax.swing.JPanel();
        PenjualanIcon = new javax.swing.JLabel();
        PenjualanLabel = new javax.swing.JLabel();
        Separator1 = new javax.swing.JPanel();
        Separator2 = new javax.swing.JPanel();
        Separator3 = new javax.swing.JPanel();
        Separator4 = new javax.swing.JPanel();
        Separator5 = new javax.swing.JPanel();
        Separator6 = new javax.swing.JPanel();
        Separator7 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        BreadcrumbPanel = new javax.swing.JPanel();
        lblBreadcrumb = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pakanaria - Dashboard");
        setBounds(new java.awt.Rectangle(0, 0, 1280, 800));
        setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setName("dashboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        HeaderPanel.setBackground(new java.awt.Color(46, 52, 64));
        HeaderPanel.setForeground(new java.awt.Color(46, 52, 64));
        HeaderPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        HeaderPanel.setMaximumSize(new java.awt.Dimension(1280, 50));
        HeaderPanel.setMinimumSize(new java.awt.Dimension(1280, 50));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(1280, 50));
        HeaderPanel.setLayout(new java.awt.GridBagLayout());

        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-menu.png"))); // NOI18N
        btnMinimize.setMaximumSize(new java.awt.Dimension(75, 40));
        btnMinimize.setMinimumSize(new java.awt.Dimension(75, 40));
        btnMinimize.setPreferredSize(new java.awt.Dimension(75, 40));
        HeaderPanel.add(btnMinimize, new java.awt.GridBagConstraints());

        lblHeader.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHeader.setText("P A K A N A R I A");
        lblHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHeader.setMaximumSize(new java.awt.Dimension(1146, 40));
        lblHeader.setMinimumSize(new java.awt.Dimension(1146, 40));
        lblHeader.setPreferredSize(new java.awt.Dimension(1146, 40));
        HeaderPanel.add(lblHeader, new java.awt.GridBagConstraints());

        btnLogout.setBackground(new java.awt.Color(46, 52, 64));
        btnLogout.setForeground(new java.awt.Color(46, 52, 64));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMaximumSize(new java.awt.Dimension(59, 40));
        btnLogout.setMinimumSize(new java.awt.Dimension(59, 40));
        btnLogout.setOpaque(true);
        btnLogout.setPreferredSize(new java.awt.Dimension(59, 40));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        HeaderPanel.add(btnLogout, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(HeaderPanel, gridBagConstraints);

        SidebarPanel.setBackground(new java.awt.Color(216, 222, 233));
        SidebarPanel.setForeground(new java.awt.Color(216, 222, 233));
        SidebarPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        SidebarPanel.setMaximumSize(new java.awt.Dimension(300, 750));
        SidebarPanel.setMinimumSize(new java.awt.Dimension(300, 750));
        SidebarPanel.setLayout(new java.awt.GridBagLayout());

        UserPanel.setBackground(new java.awt.Color(59, 66, 82));
        UserPanel.setForeground(new java.awt.Color(59, 66, 82));
        UserPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        UserPanel.setMaximumSize(new java.awt.Dimension(300, 200));
        UserPanel.setMinimumSize(new java.awt.Dimension(300, 200));
        UserPanel.setPreferredSize(new java.awt.Dimension(300, 200));
        UserPanel.setLayout(new java.awt.GridBagLayout());

        UserPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/user.png"))); // NOI18N
        UserPanel.add(UserPhoto, new java.awt.GridBagConstraints());

        SidebarPanel.add(UserPanel, new java.awt.GridBagConstraints());

        NavigationPanel.setBackground(new java.awt.Color(59, 66, 82));
        NavigationPanel.setForeground(new java.awt.Color(59, 66, 82));
        NavigationPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        NavigationPanel.setMaximumSize(new java.awt.Dimension(300, 550));
        NavigationPanel.setMinimumSize(new java.awt.Dimension(300, 550));
        NavigationPanel.setPreferredSize(new java.awt.Dimension(300, 550));
        NavigationPanel.setLayout(new java.awt.GridBagLayout());

        DashboardMenu.setBackground(new java.awt.Color(76, 86, 106));
        DashboardMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        DashboardMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        DashboardMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        DashboardMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMenuMouseClicked(evt);
            }
        });
        DashboardMenu.setLayout(new java.awt.GridBagLayout());

        DashboardIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-dashboard.png"))); // NOI18N
        DashboardIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        DashboardIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        DashboardIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        DashboardMenu.add(DashboardIcon, new java.awt.GridBagConstraints());

        DashboardLabel.setBackground(new java.awt.Color(255, 255, 255));
        DashboardLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        DashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DashboardLabel.setText("Dashboard");
        DashboardLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        DashboardLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        DashboardLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        DashboardMenu.add(DashboardLabel, new java.awt.GridBagConstraints());

        NavigationPanel.add(DashboardMenu, new java.awt.GridBagConstraints());

        KaryawanMenu.setBackground(new java.awt.Color(76, 86, 106));
        KaryawanMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        KaryawanMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        KaryawanMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        KaryawanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KaryawanMenuMouseClicked(evt);
            }
        });
        KaryawanMenu.setLayout(new java.awt.GridBagLayout());

        KaryawanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KaryawanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-karyawan.png"))); // NOI18N
        KaryawanIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        KaryawanIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        KaryawanIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        KaryawanMenu.add(KaryawanIcon, new java.awt.GridBagConstraints());

        KaryawanLabel.setBackground(new java.awt.Color(255, 255, 255));
        KaryawanLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        KaryawanLabel.setForeground(new java.awt.Color(255, 255, 255));
        KaryawanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        KaryawanLabel.setText("Karyawan");
        KaryawanLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        KaryawanLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        KaryawanLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        KaryawanMenu.add(KaryawanLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        NavigationPanel.add(KaryawanMenu, gridBagConstraints);

        KredensialMenu.setBackground(new java.awt.Color(76, 86, 106));
        KredensialMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        KredensialMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        KredensialMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        KredensialMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KredensialMenuMouseClicked(evt);
            }
        });
        KredensialMenu.setLayout(new java.awt.GridBagLayout());

        KredensialIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KredensialIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-kredensial.png"))); // NOI18N
        KredensialIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        KredensialIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        KredensialIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        KredensialMenu.add(KredensialIcon, new java.awt.GridBagConstraints());

        KredensialLabel.setBackground(new java.awt.Color(255, 255, 255));
        KredensialLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        KredensialLabel.setForeground(new java.awt.Color(255, 255, 255));
        KredensialLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        KredensialLabel.setText("Kredensial");
        KredensialLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        KredensialLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        KredensialLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        KredensialMenu.add(KredensialLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        NavigationPanel.add(KredensialMenu, gridBagConstraints);

        SupplierMenu.setBackground(new java.awt.Color(76, 86, 106));
        SupplierMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        SupplierMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        SupplierMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        SupplierMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierMenuMouseClicked(evt);
            }
        });
        SupplierMenu.setLayout(new java.awt.GridBagLayout());

        SupplierIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SupplierIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-supplier.png"))); // NOI18N
        SupplierIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        SupplierIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        SupplierIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        SupplierMenu.add(SupplierIcon, new java.awt.GridBagConstraints());

        SupplierLabel.setBackground(new java.awt.Color(255, 255, 255));
        SupplierLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        SupplierLabel.setForeground(new java.awt.Color(255, 255, 255));
        SupplierLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SupplierLabel.setText("Supplier Pakan");
        SupplierLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        SupplierLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        SupplierLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        SupplierMenu.add(SupplierLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        NavigationPanel.add(SupplierMenu, gridBagConstraints);

        SatuanMenu.setBackground(new java.awt.Color(76, 86, 106));
        SatuanMenu.setForeground(new java.awt.Color(94, 129, 172));
        SatuanMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        SatuanMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        SatuanMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        SatuanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SatuanMenuMouseClicked(evt);
            }
        });
        SatuanMenu.setLayout(new java.awt.GridBagLayout());

        SatuanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SatuanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-satuan.png"))); // NOI18N
        SatuanIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        SatuanIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        SatuanIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        SatuanMenu.add(SatuanIcon, new java.awt.GridBagConstraints());

        SatuanLabel.setBackground(new java.awt.Color(255, 255, 255));
        SatuanLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        SatuanLabel.setForeground(new java.awt.Color(255, 255, 255));
        SatuanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SatuanLabel.setText("Satuan Pakan");
        SatuanLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        SatuanLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        SatuanLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        SatuanMenu.add(SatuanLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        NavigationPanel.add(SatuanMenu, gridBagConstraints);

        PakanMenu.setBackground(new java.awt.Color(76, 86, 106));
        PakanMenu.setForeground(new java.awt.Color(94, 129, 172));
        PakanMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        PakanMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        PakanMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        PakanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PakanMenuMouseClicked(evt);
            }
        });
        PakanMenu.setLayout(new java.awt.GridBagLayout());

        PakanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PakanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-pakan.png"))); // NOI18N
        PakanIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        PakanIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        PakanIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        PakanMenu.add(PakanIcon, new java.awt.GridBagConstraints());

        PakanLabel.setBackground(new java.awt.Color(255, 255, 255));
        PakanLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        PakanLabel.setForeground(new java.awt.Color(255, 255, 255));
        PakanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PakanLabel.setText("Produk Pakan");
        PakanLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        PakanLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        PakanLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        PakanMenu.add(PakanLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        NavigationPanel.add(PakanMenu, gridBagConstraints);

        PersediaanMenu.setBackground(new java.awt.Color(76, 86, 106));
        PersediaanMenu.setForeground(new java.awt.Color(94, 129, 172));
        PersediaanMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        PersediaanMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        PersediaanMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        PersediaanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersediaanMenuMouseClicked(evt);
            }
        });
        PersediaanMenu.setLayout(new java.awt.GridBagLayout());

        PersediaanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersediaanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-persediaan.png"))); // NOI18N
        PersediaanIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        PersediaanIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        PersediaanIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        PersediaanMenu.add(PersediaanIcon, new java.awt.GridBagConstraints());

        PersediaanLabel.setBackground(new java.awt.Color(255, 255, 255));
        PersediaanLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        PersediaanLabel.setForeground(new java.awt.Color(255, 255, 255));
        PersediaanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PersediaanLabel.setText("Persediaan Pakan");
        PersediaanLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        PersediaanLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        PersediaanLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        PersediaanMenu.add(PersediaanLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        NavigationPanel.add(PersediaanMenu, gridBagConstraints);

        PenjualanMenu.setBackground(new java.awt.Color(76, 86, 106));
        PenjualanMenu.setForeground(new java.awt.Color(94, 129, 172));
        PenjualanMenu.setMaximumSize(new java.awt.Dimension(250, 50));
        PenjualanMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        PenjualanMenu.setPreferredSize(new java.awt.Dimension(250, 50));
        PenjualanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PenjualanMenuMouseClicked(evt);
            }
        });
        PenjualanMenu.setLayout(new java.awt.GridBagLayout());

        PenjualanIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PenjualanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/icon-penjualan.png"))); // NOI18N
        PenjualanIcon.setMaximumSize(new java.awt.Dimension(50, 40));
        PenjualanIcon.setMinimumSize(new java.awt.Dimension(50, 40));
        PenjualanIcon.setPreferredSize(new java.awt.Dimension(50, 40));
        PenjualanMenu.add(PenjualanIcon, new java.awt.GridBagConstraints());

        PenjualanLabel.setBackground(new java.awt.Color(255, 255, 255));
        PenjualanLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        PenjualanLabel.setForeground(new java.awt.Color(255, 255, 255));
        PenjualanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PenjualanLabel.setText("Penjualan Pakan");
        PenjualanLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        PenjualanLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        PenjualanLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        PenjualanMenu.add(PenjualanLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        NavigationPanel.add(PenjualanMenu, gridBagConstraints);

        Separator1.setBackground(new java.awt.Color(59, 66, 82));
        Separator1.setForeground(new java.awt.Color(59, 66, 82));
        Separator1.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator1.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator1.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator1Layout = new javax.swing.GroupLayout(Separator1);
        Separator1.setLayout(Separator1Layout);
        Separator1Layout.setHorizontalGroup(
            Separator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        Separator1Layout.setVerticalGroup(
            Separator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        NavigationPanel.add(Separator1, gridBagConstraints);

        Separator2.setBackground(new java.awt.Color(59, 66, 82));
        Separator2.setForeground(new java.awt.Color(59, 66, 82));
        Separator2.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator2.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator2.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator2Layout = new javax.swing.GroupLayout(Separator2);
        Separator2.setLayout(Separator2Layout);
        Separator2Layout.setHorizontalGroup(
            Separator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        Separator2Layout.setVerticalGroup(
            Separator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        NavigationPanel.add(Separator2, gridBagConstraints);

        Separator3.setBackground(new java.awt.Color(59, 66, 82));
        Separator3.setForeground(new java.awt.Color(59, 66, 82));
        Separator3.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator3.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator3.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator3Layout = new javax.swing.GroupLayout(Separator3);
        Separator3.setLayout(Separator3Layout);
        Separator3Layout.setHorizontalGroup(
            Separator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        Separator3Layout.setVerticalGroup(
            Separator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        NavigationPanel.add(Separator3, gridBagConstraints);

        Separator4.setBackground(new java.awt.Color(59, 66, 82));
        Separator4.setForeground(new java.awt.Color(59, 66, 82));
        Separator4.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator4.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator4.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator4Layout = new javax.swing.GroupLayout(Separator4);
        Separator4.setLayout(Separator4Layout);
        Separator4Layout.setHorizontalGroup(
            Separator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        Separator4Layout.setVerticalGroup(
            Separator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        NavigationPanel.add(Separator4, gridBagConstraints);

        Separator5.setBackground(new java.awt.Color(59, 66, 82));
        Separator5.setForeground(new java.awt.Color(59, 66, 82));
        Separator5.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator5.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator5.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator5Layout = new javax.swing.GroupLayout(Separator5);
        Separator5.setLayout(Separator5Layout);
        Separator5Layout.setHorizontalGroup(
            Separator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Separator5Layout.setVerticalGroup(
            Separator5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        NavigationPanel.add(Separator5, gridBagConstraints);

        Separator6.setBackground(new java.awt.Color(59, 66, 82));
        Separator6.setForeground(new java.awt.Color(59, 66, 82));
        Separator6.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator6.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator6.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator6Layout = new javax.swing.GroupLayout(Separator6);
        Separator6.setLayout(Separator6Layout);
        Separator6Layout.setHorizontalGroup(
            Separator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Separator6Layout.setVerticalGroup(
            Separator6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        NavigationPanel.add(Separator6, gridBagConstraints);

        Separator7.setBackground(new java.awt.Color(59, 66, 82));
        Separator7.setForeground(new java.awt.Color(59, 66, 82));
        Separator7.setMaximumSize(new java.awt.Dimension(250, 15));
        Separator7.setMinimumSize(new java.awt.Dimension(250, 15));
        Separator7.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout Separator7Layout = new javax.swing.GroupLayout(Separator7);
        Separator7.setLayout(Separator7Layout);
        Separator7Layout.setHorizontalGroup(
            Separator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Separator7Layout.setVerticalGroup(
            Separator7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        NavigationPanel.add(Separator7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        SidebarPanel.add(NavigationPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(SidebarPanel, gridBagConstraints);

        MainPanel.setBackground(new java.awt.Color(249, 249, 249));
        MainPanel.setForeground(new java.awt.Color(249, 249, 249));
        MainPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        MainPanel.setMaximumSize(new java.awt.Dimension(980, 750));
        MainPanel.setMinimumSize(new java.awt.Dimension(980, 750));
        MainPanel.setPreferredSize(new java.awt.Dimension(980, 750));
        MainPanel.setLayout(new java.awt.GridBagLayout());

        BreadcrumbPanel.setBackground(new java.awt.Color(249, 249, 249));
        BreadcrumbPanel.setForeground(new java.awt.Color(249, 249, 249));
        BreadcrumbPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        BreadcrumbPanel.setMinimumSize(new java.awt.Dimension(980, 50));
        BreadcrumbPanel.setPreferredSize(new java.awt.Dimension(980, 50));
        BreadcrumbPanel.setLayout(new java.awt.GridBagLayout());

        lblBreadcrumb.setBackground(new java.awt.Color(216, 222, 233));
        lblBreadcrumb.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        lblBreadcrumb.setForeground(new java.awt.Color(76, 86, 106));
        lblBreadcrumb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBreadcrumb.setText("Dashboard");
        lblBreadcrumb.setMaximumSize(new java.awt.Dimension(940, 40));
        lblBreadcrumb.setMinimumSize(new java.awt.Dimension(940, 40));
        lblBreadcrumb.setPreferredSize(new java.awt.Dimension(940, 40));
        BreadcrumbPanel.add(lblBreadcrumb, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MainPanel.add(BreadcrumbPanel, gridBagConstraints);

        ContentPanel.setBackground(new java.awt.Color(249, 249, 249));
        ContentPanel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        ContentPanel.setMaximumSize(new java.awt.Dimension(980, 700));
        ContentPanel.setMinimumSize(new java.awt.Dimension(980, 700));

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        MainPanel.add(ContentPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(MainPanel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        View.Login obj = new View.Login();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void DashboardMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Dashboard");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentStats()).setVisible(true);
    }//GEN-LAST:event_DashboardMenuMouseClicked

    private void KaryawanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KaryawanMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Karyawan");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentKaryawan()).setVisible(true);
    }//GEN-LAST:event_KaryawanMenuMouseClicked

    private void KredensialMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KredensialMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Kredensial");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentKredensial()).setVisible(true);
    }//GEN-LAST:event_KredensialMenuMouseClicked

    private void SupplierMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Supplier Pakan");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentSupplier()).setVisible(true);
    }//GEN-LAST:event_SupplierMenuMouseClicked

    private void SatuanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SatuanMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Satuan Pakan");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentSatuan()).setVisible(true);
    }//GEN-LAST:event_SatuanMenuMouseClicked

    private void PakanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PakanMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Produk Pakan");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentPakan()).setVisible(true);
    }//GEN-LAST:event_PakanMenuMouseClicked

    private void PersediaanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersediaanMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Persediaan Pakan");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentPersediaan()).setVisible(true);
    }//GEN-LAST:event_PersediaanMenuMouseClicked

    private void PenjualanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenjualanMenuMouseClicked
        // TODO add your handling code here:
        lblBreadcrumb.setText("Penjualan Pakan");
        ContentPanel.removeAll();
        ContentPanel.add(new View.ContentPenjualan()).setVisible(true);
    }//GEN-LAST:event_PenjualanMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BreadcrumbPanel;
    private javax.swing.JDesktopPane ContentPanel;
    private javax.swing.JLabel DashboardIcon;
    private javax.swing.JLabel DashboardLabel;
    private javax.swing.JPanel DashboardMenu;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel KaryawanIcon;
    private javax.swing.JLabel KaryawanLabel;
    private javax.swing.JPanel KaryawanMenu;
    private javax.swing.JLabel KredensialIcon;
    private javax.swing.JLabel KredensialLabel;
    private javax.swing.JPanel KredensialMenu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel NavigationPanel;
    private javax.swing.JLabel PakanIcon;
    private javax.swing.JLabel PakanLabel;
    private javax.swing.JPanel PakanMenu;
    private javax.swing.JLabel PenjualanIcon;
    private javax.swing.JLabel PenjualanLabel;
    private javax.swing.JPanel PenjualanMenu;
    private javax.swing.JLabel PersediaanIcon;
    private javax.swing.JLabel PersediaanLabel;
    private javax.swing.JPanel PersediaanMenu;
    private javax.swing.JLabel SatuanIcon;
    private javax.swing.JLabel SatuanLabel;
    private javax.swing.JPanel SatuanMenu;
    private javax.swing.JPanel Separator1;
    private javax.swing.JPanel Separator2;
    private javax.swing.JPanel Separator3;
    private javax.swing.JPanel Separator4;
    private javax.swing.JPanel Separator5;
    private javax.swing.JPanel Separator6;
    private javax.swing.JPanel Separator7;
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JLabel SupplierIcon;
    private javax.swing.JLabel SupplierLabel;
    private javax.swing.JPanel SupplierMenu;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JLabel UserPhoto;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel lblBreadcrumb;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
