/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author enigma
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelImage = new javax.swing.JPanel();
        AppIcon = new javax.swing.JLabel();
        AppName = new javax.swing.JLabel();
        Separator = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        btnBatal = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pakanaria - Sign In");
        setBackground(new java.awt.Color(249, 249, 249));
        setBounds(new java.awt.Rectangle(0, 0, 900, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(249, 249, 249));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setName("login"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        PanelImage.setBackground(new java.awt.Color(59, 66, 82));
        PanelImage.setForeground(new java.awt.Color(249, 249, 249));
        PanelImage.setMaximumSize(new java.awt.Dimension(200, 600));
        PanelImage.setPreferredSize(new java.awt.Dimension(200, 600));
        PanelImage.setLayout(new java.awt.GridBagLayout());

        AppIcon.setBackground(new java.awt.Color(249, 249, 249));
        AppIcon.setForeground(new java.awt.Color(249, 249, 249));
        AppIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/storage/app-image.png"))); // NOI18N
        PanelImage.add(AppIcon, new java.awt.GridBagConstraints());

        AppName.setBackground(new java.awt.Color(249, 249, 249));
        AppName.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        AppName.setForeground(new java.awt.Color(249, 249, 249));
        AppName.setText("P A K A N A R I A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        PanelImage.add(AppName, gridBagConstraints);

        Separator.setBackground(new java.awt.Color(59, 66, 82));
        Separator.setForeground(new java.awt.Color(59, 66, 82));
        Separator.setMinimumSize(new java.awt.Dimension(100, 50));
        Separator.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout SeparatorLayout = new javax.swing.GroupLayout(Separator);
        Separator.setLayout(SeparatorLayout);
        SeparatorLayout.setHorizontalGroup(
            SeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        SeparatorLayout.setVerticalGroup(
            SeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        PanelImage.add(Separator, gridBagConstraints);

        getContentPane().add(PanelImage);

        PanelForm.setBackground(new java.awt.Color(249, 249, 249));
        PanelForm.setForeground(new java.awt.Color(249, 249, 249));
        PanelForm.setMaximumSize(new java.awt.Dimension(700, 32767));
        PanelForm.setPreferredSize(new java.awt.Dimension(700, 600));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(76, 86, 106));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LOGIN");

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(76, 86, 106));
        lblUsername.setText("USERNAME");

        lblPassword.setBackground(new java.awt.Color(0, 0, 0));
        lblPassword.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(76, 86, 106));
        lblPassword.setText("PASSWORD");

        fieldUsername.setBackground(new java.awt.Color(59, 66, 82));
        fieldUsername.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(249, 249, 249));
        fieldUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 66, 82), 10));
        fieldUsername.setCaretColor(new java.awt.Color(249, 249, 249));
        fieldUsername.setMargin(new java.awt.Insets(0, 0, 0, 0));
        fieldUsername.setPreferredSize(new java.awt.Dimension(500, 27));

        fieldPassword.setBackground(new java.awt.Color(59, 66, 82));
        fieldPassword.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(249, 249, 249));
        fieldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 66, 82), 10));
        fieldPassword.setCaretColor(new java.awt.Color(249, 249, 249));

        btnBatal.setBackground(new java.awt.Color(208, 135, 112));
        btnBatal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(249, 249, 249));
        btnBatal.setText("BATAL");
        btnBatal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(208, 135, 112), 10));
        btnBatal.setContentAreaFilled(false);
        btnBatal.setFocusPainted(false);
        btnBatal.setOpaque(true);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(59, 66, 82));
        btnLogin.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(249, 249, 249));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 66, 82), 10));
        btnLogin.setContentAreaFilled(false);
        btnLogin.setFocusPainted(false);
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(191, 97, 106));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("⨉");
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setFocusPainted(false);
        btnClose.setMaximumSize(new java.awt.Dimension(45, 45));
        btnClose.setMinimumSize(new java.awt.Dimension(45, 45));
        btnClose.setOpaque(true);
        btnClose.setPreferredSize(new java.awt.Dimension(45, 45));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(fieldPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelForm);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        fieldUsername.setText("");
        fieldPassword.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = fieldUsername.getText();
        String password = classes.Helper.CreateSha256(fieldPassword.getText());
        var res = App.Auth.Login(username, password);
        if (res) {
            JOptionPane.showMessageDialog(rootPane, "Proses Login Berhasil!", "Pemberitahuan", JOptionPane.OK_OPTION);
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Proses Login Gagal!", "Pemberitahuan", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispatchEvent ( new WindowEvent (
            this, WindowEvent.WINDOW_CLOSING
        ));
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppIcon;
    private javax.swing.JLabel AppName;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelImage;
    private javax.swing.JPanel Separator;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
